export const options = [
  // Популярные страны
  { value: "us", label: "США" },
  { value: "cn", label: "Китай" },
  { value: "in", label: "Индия" },
  { value: "ru", label: "Россия" },
  { value: "gb", label: "Великобритания" },
  { value: "de", label: "Германия" },
  { value: "jp", label: "Япония" },
  { value: "fr", label: "Франция" },
  { value: "br", label: "Бразилия" },
  { value: "it", label: "Италия" },

  // Остальные страны в алфавитном порядке
  { value: "af", label: "Афганистан" },
  { value: "al", label: "Албания" },
  { value: "dz", label: "Алжир" },
  { value: "ad", label: "Андорра" },
  { value: "ao", label: "Ангола" },
  { value: "ag", label: "Антигуа и Барбуда" },
  { value: "ar", label: "Аргентина" },
  { value: "am", label: "Армения" },
  { value: "au", label: "Австралия" },
  { value: "at", label: "Австрия" },
  { value: "az", label: "Азербайджан" },
  { value: "bs", label: "Багамы" },
  { value: "bh", label: "Бахрейн" },
  { value: "bd", label: "Бангладеш" },
  { value: "bb", label: "Барбадос" },
  { value: "by", label: "Беларусь" },
  { value: "be", label: "Бельгия" },
  { value: "bz", label: "Белиз" },
  { value: "bj", label: "Бенин" },
  { value: "bt", label: "Бутан" },
  { value: "bo", label: "Боливия" },
  { value: "ba", label: "Босния и Герцеговина" },
  { value: "bw", label: "Ботсвана" },
  { value: "bn", label: "Бруней" },
  { value: "bg", label: "Болгария" },
  { value: "bf", label: "Буркина-Фасо" },
  { value: "bi", label: "Бурунди" },
  { value: "kh", label: "Камбоджа" },
  { value: "cm", label: "Камерун" },
  { value: "ca", label: "Канада" },
  { value: "cv", label: "Кабо-Верде" },
  { value: "cf", label: "Центральноафриканская Республика" },
  { value: "td", label: "Чад" },
  { value: "cl", label: "Чили" },
  { value: "co", label: "Колумбия" },
  { value: "km", label: "Коморы" },
  { value: "cg", label: "Конго" },
  { value: "cd", label: "Демократическая Республика Конго" },
  { value: "cr", label: "Коста-Рика" },
  { value: "ci", label: "Кот-д'Ивуар" },
  { value: "hr", label: "Хорватия" },
  { value: "cu", label: "Куба" },
  { value: "cy", label: "Кипр" },
  { value: "cz", label: "Чехия" },
  { value: "dk", label: "Дания" },
  { value: "dj", label: "Джибути" },
  { value: "dm", label: "Доминика" },
  { value: "do", label: "Доминиканская Республика" },
  { value: "ec", label: "Эквадор" },
  { value: "eg", label: "Египет" },
  { value: "sv", label: "Сальвадор" },
  { value: "gq", label: "Экваториальная Гвинея" },
  { value: "er", label: "Эритрея" },
  { value: "ee", label: "Эстония" },
  { value: "et", label: "Эфиопия" },
  { value: "fj", label: "Фиджи" },
  { value: "fi", label: "Финляндия" },
  { value: "ga", label: "Габон" },
  { value: "gm", label: "Гамбия" },
  { value: "ge", label: "Грузия" },
  { value: "gh", label: "Гана" },
  { value: "gr", label: "Греция" },
  { value: "gd", label: "Гренада" },
  { value: "gt", label: "Гватемала" },
  { value: "gn", label: "Гвинея" },
  { value: "gw", label: "Гвинея-Бисау" },
  { value: "gy", label: "Гайана" },
  { value: "ht", label: "Гаити" },
  { value: "hn", label: "Гондурас" },
  { value: "hu", label: "Венгрия" },
  { value: "is", label: "Исландия" },
  { value: "id", label: "Индонезия" },
  { value: "ir", label: "Иран" },
  { value: "iq", label: "Ирак" },
  { value: "ie", label: "Ирландия" },
  { value: "il", label: "Израиль" },
  { value: "jm", label: "Ямайка" },
  { value: "jo", label: "Иордания" },
  { value: "kz", label: "Казахстан" },
  { value: "ke", label: "Кения" },
  { value: "ki", label: "Кирибати" },
  { value: "kp", label: "Северная Корея" },
  { value: "kr", label: "Южная Корея" },
  { value: "kw", label: "Кувейт" },
  { value: "kg", label: "Кыргызстан" },
  { value: "la", label: "Лаос" },
  { value: "lv", label: "Латвия" },
  { value: "lb", label: "Ливан" },
  { value: "ls", label: "Лесото" },
  { value: "lr", label: "Либерия" },
  { value: "ly", label: "Ливия" },
  { value: "li", label: "Лихтенштейн" },
  { value: "lt", label: "Литва" },
  { value: "lu", label: "Люксембург" },
  { value: "mg", label: "Мадагаскар" },
  { value: "mw", label: "Малави" },
  { value: "my", label: "Малайзия" },
  { value: "mv", label: "Мальдивы" },
  { value: "ml", label: "Мали" },
  { value: "mt", label: "Мальта" },
  { value: "mh", label: "Маршалловы Острова" },
  { value: "mr", label: "Мавритания" },
  { value: "mu", label: "Маврикий" },
  { value: "mx", label: "Мексика" },
  { value: "fm", label: "Микронезия" },
  { value: "md", label: "Молдова" },
  { value: "mc", label: "Монако" },
  { value: "mn", label: "Монголия" },
  { value: "me", label: "Черногория" },
  { value: "ma", label: "Марокко" },
  { value: "mz", label: "Мозамбик" },
  { value: "mm", label: "Мьянма" },
  { value: "na", label: "Намибия" },
  { value: "nr", label: "Науру" },
  { value: "np", label: "Непал" },
  { value: "nl", label: "Нидерланды" },
  { value: "nz", label: "Новая Зеландия" },
  { value: "ni", label: "Никарагуа" },
  { value: "ne", label: "Нигер" },
  { value: "ng", label: "Нигерия" },
  { value: "mk", label: "Северная Македония" },
  { value: "no", label: "Норвегия" },
  { value: "om", label: "Оман" },
  { value: "pk", label: "Пакистан" },
  { value: "pw", label: "Палау" },
  { value: "pa", label: "Панама" },
  { value: "pg", label: "Папуа-Новая Гвинея" },
  { value: "py", label: "Парагвай" },
  { value: "pe", label: "Перу" },
  { value: "ph", label: "Филиппины" },
  { value: "pl", label: "Польша" },
  { value: "pt", label: "Португалия" },
  { value: "qa", label: "Катар" },
  { value: "ro", label: "Румыния" },
  { value: "rw", label: "Руанда" },
  { value: "kn", label: "Сент-Китс и Невис" },
  { value: "lc", label: "Сент-Люсия" },
  { value: "vc", label: "Сент-Винсент и Гренадины" },
  { value: "ws", label: "Самоа" },
  { value: "sm", label: "Сан-Марино" },
  { value: "st", label: "Сан-Томе и Принсипи" },
  { value: "sa", label: "Саудовская Аравия" },
  { value: "sn", label: "Сенегал" },
  { value: "rs", label: "Сербия" },
  { value: "sc", label: "Сейшельские Острова" },
  { value: "sl", label: "Сьерра-Леоне" },
  { value: "sg", label: "Сингапур" },
  { value: "sk", label: "Словакия" },
  { value: "si", label: "Словения" },
  { value: "sb", label: "Соломоновы Острова" },
  { value: "so", label: "Сомали" },
  { value: "za", label: "Южная Африка" },
  { value: "ss", label: "Южный Судан" },
  { value: "es", label: "Испания" },
  { value: "lk", label: "Шри-Ланка" },
  { value: "sd", label: "Судан" },
  { value: "sr", label: "Суринам" },
  { value: "sz", label: "Эсватини" },
  { value: "se", label: "Швеция" },
  { value: "ch", label: "Швейцария" },
  { value: "sy", label: "Сирия" },
  { value: "tw", label: "Тайвань" },
  { value: "tj", label: "Таджикистан" },
  { value: "tz", label: "Танзания" },
  { value: "th", label: "Таиланд" },
  { value: "tl", label: "Тимор-Лешти" },
  { value: "tg", label: "Того" },
  { value: "to", label: "Тонга" },
  { value: "tt", label: "Тринидад и Тобаго" },
  { value: "tn", label: "Тунис" },
  { value: "tr", label: "Турция" },
  { value: "tm", label: "Туркменистан" },
  { value: "tv", label: "Тувалу" },
  { value: "ug", label: "Уганда" },
  { value: "ua", label: "Украина" },
  { value: "ae", label: "Объединенные Арабские Эмираты" },
  { value: "uy", label: "Уругвай" },
  { value: "uz", label: "Узбекистан" },
  { value: "vu", label: "Вануату" },
  { value: "va", label: "Ватикан" },
  { value: "ve", label: "Венесуэла" },
  { value: "vn", label: "Вьетнам" },
  { value: "ye", label: "Йемен" },
  { value: "zm", label: "Замбия" },
  { value: "zw", label: "Зимбабве" },
];
